---
language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - jruby-18mode
  - jruby-19mode
  - 1.9.3
  - 2.0.0-p648 # macOS
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6
  - ruby-head
  - jruby-head
before_install: gem install bundler -v '~> 1.14' --conservative
